project:
  name: Donut Admin
  version: 2.1.1
  rsaPrivateKey: MIICdwIBADANBgkqhkiG9w0BAQEFAASCAmEwggJdAgEAAoGBALH81v/GpK1KW4zQotxHwI2BVOQ+g9VcVQxnDb6Zs+t+rlS18slqjGcINYBCWvkpEyqz3jI4evmXYQn64FNR7lY1QALDwetTyi5t70vC1aSmmk2ZO3DB3PP9l+ygbkDmYy1pjP+JunkT1cbogcXL6nUNRHFSR/upwdmA/+1OeMplAgMBAAECgYAqje4Fh0PWHsIWv8dAbXNPIc3fKEcy2vmGlpkFqhAHTOl3XW0n1O6ur5rDCJphmf14JzsHvNNCG3xa+31ozlzyHvjXN2kGUW5UDW7gJm/yh8HDtyl4IK/BFv9bFbpvMkSMkThiUI1zucafmQe8e7rMMJFzM2XfFuq1ilkBzqjlAQJBAOy4cgx+SbxjtU40xxOzLAC7K1qHzas4Ocv8BsMG4iCZs2Yrh/sCQs3nYx9EEbN2PgqZpY7uFUoulisDvieiHyUCQQDAe9Tfto6dlPJjbzT7dtMqTXTeCwpkGpOwbvvBoxY4b1OGUG8gzScbmAE1U+YAH0I2WaHwuHj6RELpAHIklrpBAkEAzKN6vIAkID8WCmCnxMj8fjlP9jg2PREjLctW0RxPOZ2FsApryDuhIr0oPGws3TaX1bQTomcBcpqpaNAYf8ywHQJAJHpTSWJLfMmxde6pV86ZDjdHopztBzOSMamWxIenumI+rgGoTcsTUkNoVzbjK7rAzZQHAJu1MZimJYoUF6MJAQJBAI3q0IOgbZkDSVXlLxzNIO9QrlgDqoVjQKnlM8LL/3yXZOKTDbPSpenlJpgy5/sbrexA3S50B5gPoDMhPxiSyJY=
  rsaPublicKey: MIGfMA0GCSqGSIb3DQEBAQUAA4GNADCBiQKBgQCx/Nb/xqStSluM0KLcR8CNgVTkPoPVXFUMZw2+mbPrfq5UtfLJaoxnCDWAQlr5KRMqs94yOHr5l2EJ+uBTUe5WNUACw8HrU8oube9LwtWkpppNmTtwwdzz/ZfsoG5A5mMtaYz/ibp5E9XG6IHFy+p1DURxUkf7qcHZgP/tTnjKZQIDAQAB
  captchaExpire: 180
  # 临时目录，用于存放临时文件，之后会被删除，以/结尾
  templatePath: D:/data/templatesFile/
  tenant-ignore-tables:
    - gen_table
    - gen_table_column
    - gen_datasource
    - sys_tenant
    - sys_menu
    - sys_job
    - sys_job_log
    - sys_dict_type
    - sys_dict_data

server:
  port: 10001

spring:
  application:
    name: donut-admin
  profiles:
    active: dev
  config:
    import: classpath:file-ext.yml
  data:
    # redis 配置
    redis:
      # 连接超时时间
      timeout: 15000
      lettuce:
        pool:
          # 连接池中的最小空闲连接
          min-idle: 0
          # 连接池中的最大空闲连接
          max-idle: 10
          # 连接池的最大数据库连接数
          max-active: 20
          # #连接池最大阻塞等待时间（使用负值表示没有限制）
          max-wait: -1ms
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    druid:
      initial-size: 5
      min-idle: 5
      max-active: 20
      max-wait: 60000
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: select 'x'
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1
      use-global-data-source-stat: true
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.png,*.css,*.ico
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: false
        login-username: druid
        login-password: druid
        allow: 127.0.0.1
  servlet:
    multipart:
      max-request-size: 30MB
      max-file-size: 20MB
  threads:
    virtual:
      enabled: true
# MyBatis Plus配置
mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: cn.lenmotion.donut.**.po
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mappers/**/*Mapper.xml
  # 加载全局的配置文件
  #  configLocation: classpath:mybatis/mybatis-config.xml
  global-config:
    db-config:
      logic-delete-field: deleted
    banner: false

easy-trans:
  #启用redis缓存 如果不用redis请设置为false
  is-enable-redis: true
  #启用全局翻译(拦截所有responseBody进行自动翻译)，如果对于性能要求很高可关闭此配置
  is-enable-global: true
  #字典缓存放到redis 微服务模式请开启
  dict-use-redis: true
  # 反向翻译数据库类型 mysql
  db-type: mysql

############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: Authorization
  # token 有效期（单位：秒） 默认1天，-1 代表永久有效
  timeout: 43200
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认1小时 代表不限制，永不冻结
  active-timeout: 3600
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: false
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: random-64
  # 是否输出操作日志
  is-log: true
  # 不从cookie读取token
  is-read-cookie: false
  # token的前缀
  token-prefix: Bearer
  # 不打印sa-token的图标
  is-print: false

# springdoc-openapi项目配置
springdoc:
  # 默认是false，需要设置为true
  default-flat-param-object: true
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn